#!/usr/bin/env bash

string="$(rofi -dmenu -i -p "Cheat:" -theme ~/.config/rofi/launchers/cheat.rasi)"
# Change the terminal to the one you're using
kitty --class kitty-helper -e $HOME/bin/cheat $(echo $string)
