#!/usr/bin/env bash
#!/usr/bin/sh
word="$(rofi -dmenu -i -p "Define:" -theme ~/.config/rofi/launchers/dict.rasi)"

# Change the terminal to the one you're using
kitty --class Dicterm -e $HOME/bin/define $word
