#!/usr/bin/env bash

word="$(rofi -dmenu -i -p "Define:" -theme ~/.config/rofi/launchers/dict.rasi)"

# Change the terminal to the one you're using
kitty --class kitty-helper -e $HOME/bin/define $word
